-- BULLETS for Notes
-- vim.pack.add({
--   { src = "https://github.com/bullets-vim/bullets.vim" },
-- })
--
-- vim.g.bullets_enabled_file_types = {
--   "scratch",
--   "text",
-- }


-- ============================================================
-- CLAUDE CODE (AI)
-- ============================================================
-- vim.pack.add {
--   gh "coder/claudecode.nvim",
-- }
--
-- require("claudecode").setup({})
--
-- vim.keymap.set("n", "<leader>ac", "<cmd>ClaudeCode<cr>", { desc = "Toggle Claude" })
-- vim.keymap.set("n", "<leader>af", "<cmd>ClaudeCodeFocus<cr>", { desc = "Focus Claude" })
--
-- vim.keymap.set("n", "<leader>ar", "<cmd>ClaudeCode --resume<cr>", { desc = "Resume Claude" })
-- vim.keymap.set("n", "<leader>aC", "<cmd>ClaudeCode --continue<cr>", { desc = "Continue Claude" })
--
-- vim.keymap.set("n", "<leader>am", "<cmd>ClaudeCodeSelectModel<cr>", { desc = "Select model" })
--
-- vim.keymap.set("n", "<leader>ab", "<cmd>ClaudeCodeAdd %<cr>", { desc = "Add buffer" })
--
-- vim.keymap.set("v", "<leader>as", "<cmd>ClaudeCodeSend<cr>", { desc = "Send selection" })
--
-- vim.keymap.set("n", "<leader>aa", "<cmd>ClaudeCodeDiffAccept<cr>", { desc = "Accept diff" })
-- vim.keymap.set("n", "<leader>ad", "<cmd>ClaudeCodeDiffDeny<cr>", { desc = "Deny diff" })
--
-- -- window resizing
-- vim.keymap.set("n", "<A-h>", "<C-w><")
-- vim.keymap.set("n", "<A-l>", "<C-w>>")
-- vim.keymap.set("n", "<A-j>", "<C-w>-")
-- vim.keymap.set("n", "<A-k>", "<C-w>+")
--


-- spaceport.nvim
-- vim.pack.add({
--   { src = "https://github.com/CWood-sdf/spaceport.nvim" },
-- })
--
-- require("spaceport").setup({
--   projectHomes = {},
--   -- projectEntry = "Neotree reveal action=focus",
--   -- projectEntry = "Neotree reveal",
--   projectEntry = "enew | Neotree focus",
--   shortcuts = {
--     -- Press 'c' to instantly jump to your neovim config
--     { "c", ".config/nvim" },
--   },
--   sections = {
--     "_global_remaps",
--     {
--       lines = function()
--         return {
--           '',
--           '',
--           '',
--           '',
--           '',
--           '',
--           '',
--           "  ███╗   ██╗ ███████╗ ██████╗  ██╗   ██╗ ██╗ ███╗   ███╗",
--           "  ████╗  ██║ ██╔════╝██╔═══██╗ ██║   ██║ ██║ ████╗ ████║",
--           "  ██╔██╗ ██║ █████╗  ██║   ██║ ██║   ██║ ██║ ██╔████╔██║",
--           "  ██║╚██╗██║ ██╔══╝  ██║   ██║ ╚██╗ ██╔╝ ██║ ██║╚██╔╝██║",
--           "  ██║ ╚████║ ███████╗╚██████╔╝  ╚████╔╝  ██║ ██║ ╚═╝ ██║",
--           "  ╚═╝  ╚═══╝ ╚══════╝ ╚═════╝    ╚═══╝   ╚═╝ ╚═╝     ╚═╝",
--         }
--       end,
--     },
--     "remaps",
--     "recents",
--   },
-- })
--


-- project.nvim
-- vim.pack.add({
--     gh "DrKJeff16/project.nvim"
-- })
-- require('project').setup()
-- require('telescope').load_extension('projects')
-- vim.keymap.set('n', '<leader>sp', '<cmd>Telescope projects<cr>', { desc = '[S]earch [P]rojects' })
-- -- vim.api.nvim_create_autocmd("DirChanged", {
-- --   callback = function()
-- --     vim.cmd("Neotree reveal")
-- --   end,
-- -- })



-- alpha.nvim
-- vim.pack.add {
--   gh 'goolord/alpha-nvim'
-- }
-- require('alpha').setup(require 'alpha.themes.startify'.config)

-- vim.pack.add {
--   gh 'olimorris/persisted.nvim'
-- }
-- require('persisted').setup()



-- dashboard.nvim
-- vim.pack.add {
--   'https://github.com/nvimdev/dashboard-nvim',
--   'https://github.com/nvim-tree/nvim-web-devicons',
-- }
--
-- require('dashboard').setup {
--   theme = 'hyper',
--
--   config = {
--     week_header = {
--       enable = false,
--     },
--     header = {
--       '',
--       '███╗   ██╗██╗   ██╗██╗███╗   ███╗',
--       '████╗  ██║██║   ██║██║████╗ ████║',
--       '██╔██╗ ██║██║   ██║██║██╔████╔██║',
--       '██║╚██╗██║╚██╗ ██╔╝██║██║╚██╔╝██║',
--       '██║ ╚████║ ╚████╔╝ ██║██║ ╚═╝ ██║',
--       '╚═╝  ╚═══╝  ╚═══╝  ╚═╝╚═╝     ╚═╝',
--       '',
--     },
--
--     shortcut = {
--       {
--         desc = 'Files',
--         key = 'f',
--         action = 'Telescope find_files',
--       },
--       {
--         desc = 'Grep',
--         key = 'g',
--         action = 'Telescope live_grep',
--       },
--       {
--         desc = 'Recent',
--         key = 'r',
--         action = 'Telescope oldfiles',
--       },
--       {
--         desc = 'Config',
--         key = 'c',
--         action = 'edit $MYVIMRC',
--       },
--       {
--         desc = 'Quit',
--         key = 'q',
--         action = 'quit',
--       },
--     },
--
--     project = {
--       enable = false,
--       limit = 8,
--       label = 'Recent Projects',
--       action = function(path)
--         require('telescope.builtin').find_files {
--           cwd = path,
--         }
--       end,
--     },
--
--     mru = {
--       enable = false,
--       limit = 10,
--       label = 'Recent Files',
--       cwd_only = false,
--     },
--
--     footer = {},
--   },
-- }


-- Neotree
-- vim.pack.add {
--   {
--     src = 'https://github.com/nvim-neo-tree/neo-tree.nvim',
--     version = vim.version.range '3',
--   },
--   -- dependencies
--   'https://github.com/nvim-lua/plenary.nvim',
--   'https://github.com/MunifTanjim/nui.nvim',
--   -- optional, but recommended
--   'https://github.com/nvim-tree/nvim-web-devicons',
-- }
--
-- require('neo-tree').setup({
--   window = {
--     mappings = {
--       ["l"] = "open",
--       ["h"] = "close_node",
--       ["<CR>"] = "open",
--
--       ["Y"] = function(state)
--         local node = state.tree:get_node()
--         if not node or not node.id then
--           vim.notify("No node selected.", vim.log.levels.WARN)
--           return
--         end
--
--         if vim.fn.has("clipboard") == 0 then
--           vim.notify("System clipboard is not available.", vim.log.levels.ERROR)
--           return
--         end
--
--         local filepath = node:get_id()
--         local filename = node.name
--         local modify = vim.fn.fnamemodify
--
--         local choices = {
--           { label = "Filename without extension", value = modify(filename, ":r") },
--           { label = "Filename", value = filename },
--           { label = "Path relative to CWD", value = modify(filepath, ":.") },
--           { label = "Absolute path", value = filepath },
--           { label = "Path relative to HOME", value = modify(filepath, ":~") },
--           { label = "Extension", value = modify(filename, ":e") },
--         }
--
--         vim.ui.select(choices, {
--           prompt = "Choose what to copy:",
--           format_item = function(item)
--             return string.format("%-30s %s", item.label, item.value)
--           end,
--         }, function(choice)
--             if not choice then
--               return
--             end
--
--             vim.fn.setreg("+", choice.value)
--           vim.notify("Copied: " .. choice.value)
--         end)
--       end,
--     },
--   },
--   filesystem = {
--     hijack_netrw_behavior = "disabled",
--     filtered_items = {
--       visible = true,
--     },
--   },
-- })
--
-- vim.keymap.set(
--   "n",
--   "<leader>e",
--   "<Cmd>Neotree reveal toggle left<CR>",
--   { desc = "[E]xplorer" }
-- )
